name: AOE Continuous Deployment
on: [push]
jobs:
  AOE-CD:
    runs-on: windows-2019
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Installing modules
        run: |
          Install-Module -Name Microsoft.Graph.Authentication,Microsoft.Graph.Identity.DirectoryManagement -Scope CurrentUser -Repository PSGallery -Force
      - name: Testing PowerShell script call
        run: |
          ./Setup-LogAnalyticsWorkspaces.ps1
      - run: echo "🍏 This job's status is ${{ job.status }}."
