name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-2019
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Testing PowerShell script call
        run: |
          ./Setup-LogAnalyticsWorkspaces.ps1
      - run: echo "🍏 This job's status is ${{ job.status }}."
